
# Using sample data mpg, playing around with features of ggplot2

mpg

ggplot(data = mpg)

# Below three point to same thing. ggplot(DATA) + geom(mapping = aes(MAPPING))
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy))
ggplot(data = mpg, aes(x = displ, y = hwy)) + geom_point()
ggplot(mpg) + geom_point(aes(x = displ, y = hwy))

# Adding layer to the plot by adding features to AES

ggplot(mpg) + geom_point(mapping = aes(x = displ, y = hwy, color = class))
ggplot(mpg) + geom_point(mapping = aes(x = displ, y = hwy, alpha = class))
ggplot(mpg) + geom_point(mapping = aes(x = displ, y = hwy, shape = class))

# Features set outside the AES will impact whole, not categories
ggplot(mpg) + geom_point(mapping = aes(x = displ, y = hwy, alpha = class), color = "blue", size = 1)

ggplot(mpg) + geom_point(mapping = aes(x = displ, y = hwy, stroke = displ))

# Using facet_wrap. ~ var is categories, and nrow is number of rows on displayed panels
ggplot(mpg) + geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_wrap(~ class, nrow = 2)


* Facets are useful when aesthetics on a given data has too many discrete colors/shape etc 
# Facet grids. Use .~ var to map it in one-dimension
ggplot(mpg) + geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_grid(. ~ cyl)

# or against another to see it on a multiple-dimension
ggplot(mpg) + geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_grid(drv ~ cyl)


/*
Every geom function in ggplot2 takes a mapping argument. However, not every aesthetic works with every geom. You could set the shape of a point, but you couldn’t set the “shape” of a line. On the other hand, you could set the linetype of a line. geom_smooth() will draw a different line, with a different linetype, for each unique value of the variable that you map to linetype.

*/

# Other geom functions 
ggplot(mpg) + geom_smooth(aes(x = displ, y = hwy))

# geom_smooth have different aes features
ggplot(mpg) + geom_smooth(aes(x = displ, y = hwy, linetype = drv))

# Or we can have multiple geoms laying on another
ggplot(mpg) + 
  geom_smooth(aes(x = displ, y = hwy, linetype = drv)) +
  geom_point(aes(x = displ, y = hwy, color = drv))
  
  
# To take out repetition, we can also 
ggplot(mpg, aes(x = displ, y = hwy)) + 
  geom_point() + 
  geom_smooth()

# Placing aesthetics in geom will treat them as local mapping
ggplot(mpg, aes(x = displ, y = hwy)) + 
  geom_point(aes(color = class)) + 
  geom_smooth()

# And we can also do that for data 
ggplot(mpg, aes(x = displ, y = hwy)) + 
  geom_point(aes(color = class)) + 
  geom_smooth(data = filter(mpg, class == "subcompact"), se = FALSE)












